### PR TITLE
Fix tpmtool.poll function to build on arm64

### LINKED ISSUE #146: tpmutil does not compile with GOARCH=arm64
The error is `undefined: syscall.SYS_POLL`.

arm64 does not have `syscall.SYS_POLL`. Instead, the `syscall.SYS_PPOLL` syscall should be used. The functionality of the ppoll syscall is a superset of the poll syscall, so this should be relatively straightforward to fix.

### PR DESCRIPTION
**Pull request by rjoleary**
To achieve this, the underlying syscall is changed from poll to ppoll.
When timeout and sigmask are null, the behaviour of poll and ppoll are
equivalent (according to the man page).

Signed-off-by: Ryan O'Leary <ryanoleary@google.com>

Fixes #146

### CODE REVIEW

**Comment by josephlr** [comment]
Thanks for the fix @rjoleary, but I think it might be easier to just use [`unix.Poll`](https://godoc.org/golang.org/x/sys/unix#Poll) for `x/sys/unix`. Apparently the stdlib `syscall` package has some known issues (like the one you found) and is "frozen", see https://golang.org/doc/go1.4. 

The `unix.Poll` function also is properly implemented across all Linux arches, it even has [this `arm64` workaround](https://github.com/golang/sys/blob/b09406accb4736d857a32bf9444cd7edae2ffa79/unix/syscall_linux_arm64.go#L204-L214) to make up for the fact that `arm64` does not have the `poll` syscall.

**Comment by rjoleary** [comment]
Thanks josephlr! That's a lot better. I'll make that change.

**Comment by rjoleary** [comment]
Done!

File: tpmutil/poll_unix.go [hunk 1]
```diff
@@ -5,38 +5,29 @@ package tpmutil
...
 	)
-	_, _, errno := syscall.Syscall(syscall.SYS_POLL, uintptr(unsafe.Pointer(fd)), uintptr(numFD), uintptr(timeoutMS))
-	// Convert errno into an error, otherwise err != nil checks up the stack
-	// will hit unexpectedly on 0 errno.
-	var err error
-	if errno != 0 {
-		err = errno
+
+	_, err := unix.Poll(fds, timeout)
+	if err != nil {
```
Comment (josephlr) [inline tpmutil/poll_unix.go]: Merge these two lines

Comment (josephlr) [reply tpmutil/poll_unix.go]: Nevermind, I can just fix it.
